"use client";

import { Button } from "@/components/ui/button";
import { Eye, Pencil } from "lucide-react";
import { useState } from "react";

// function MermaidDiagram({ code }: { code: string }) {
//   const id = useId().replace(/:/g, "");
//   const ref = useRef<HTMLDivElement>(null);
//   const [svg, setSvg] = useState<string | null>(null);
//   const [error, setError] = useState<string | null>(null);

//   useEffect(() => {
//     let cancelled = false;
//     async function render() {
//       try {
//         const mermaid = (await import("mermaid")).default;
//         mermaid.initialize({ startOnLoad: false, theme: "default" });
//         const { svg: rendered } = await mermaid.render(`mermaid-${id}`, code);
//         if (!cancelled) setSvg(rendered);
//       } catch (e) {
//         if (!cancelled)
//           setError(e instanceof Error ? e.message : "Render error");
//       }
//     }
//     render();
//     return () => {
//       cancelled = true;
//     };
//   }, [code, id]);

//   if (error) {
//     return (
//       <pre className="rounded border border-destructive/40 bg-destructive/5 p-3 text-xs text-destructive overflow-x-auto">
//         {error}
//       </pre>
//     );
//   }

//   if (!svg) {
//     return (
//       <div className="flex h-16 items-center justify-center rounded border bg-muted text-xs text-muted-foreground">
//         Rendering diagram…
//       </div>
//     );
//   }

//   return (
//     <div
//       ref={ref}
//       className="overflow-x-auto rounded border bg-muted/30 p-3"
//       // SVG is generated by mermaid (trusted), not user-controlled HTML
//       dangerouslySetInnerHTML={{ __html: svg }}
//     />
//   );
// }

// function MarkdownPreview({ content }: { content: string }) {
//   return (
//     <ReactMarkdown
//       remarkPlugins={[remarkGfm]}
//       className="prose prose-sm dark:prose-invert max-w-none"
//       components={{
//         code({ className, children, ...props }) {
//           const match = /language-(\w+)/.exec(className ?? "");
//           const lang = match?.[1];
//           const code = String(children).replace(/\n$/, "");

//           if (lang === "mermaid") {
//             return <MermaidDiagram code={code} />;
//           }

//           // Inline code
//           if (!className) {
//             return (
//               <code
//                 className="rounded bg-muted px-1 py-0.5 font-mono text-[0.85em]"
//                 {...props}
//               >
//                 {children}
//               </code>
//             );
//           }

//           // Fenced code block
//           return (
//             <pre className="overflow-x-auto rounded border bg-muted p-3">
//               <code className={cn("font-mono text-sm", className)} {...props}>
//                 {children}
//               </code>
//             </pre>
//           );
//         },
//         table({ children }) {
//           return (
//             <div className="overflow-x-auto">
//               <table className="w-full text-sm border-collapse border">
//                 {children}
//               </table>
//             </div>
//           );
//         },
//         th({ children }) {
//           return (
//             <th className="border px-3 py-1.5 bg-muted text-left font-semibold">
//               {children}
//             </th>
//           );
//         },
//         td({ children }) {
//           return <td className="border px-3 py-1.5">{children}</td>;
//         },
//       }}
//     >
//       {content}
//     </ReactMarkdown>
//   );
// }

interface SpecMarkdownEditorProps {
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  minHeight?: string;
}

export function SpecMarkdownEditor({
  value,
  onChange,
  placeholder = "Escribe el contenido en Markdown…",
  minHeight = "300px",
}: SpecMarkdownEditorProps) {
  const [mode, setMode] = useState<"edit" | "preview">("edit");

  return (
    <div className="space-y-2">
      {/* Toggle bar */}
      <div className="flex items-center gap-1 border-b pb-1">
        <Button
          type="button"
          size="sm"
          variant={mode === "edit" ? "secondary" : "ghost"}
          onClick={() => setMode("edit")}
          className="h-7 px-2 text-xs"
        >
          <Pencil className="mr-1 h-3 w-3" />
          Editar
        </Button>
        <Button
          type="button"
          size="sm"
          variant={mode === "preview" ? "secondary" : "ghost"}
          onClick={() => setMode("preview")}
          className="h-7 px-2 text-xs"
        >
          <Eye className="mr-1 h-3 w-3" />
          Preview
        </Button>
      </div>

      {mode === "edit" ? (
        <textarea
          className="w-full resize-y rounded-md border bg-background px-3 py-2 font-mono text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring"
          style={{ minHeight }}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder={placeholder}
          spellCheck={false}
        />
      ) : null}
    </div>
  );
}
